### ISSUE TITLE
Are consumers able to override default Codable conditional conformances?

### ISSUE THREAD

**Issue by Killectro** [pointfreeco/swift-tagged#13]
I have a user id that, for legacy reasons, can come back as either a `String` or an `Int` and when adding `Tagged` to handle this case I was hoping to extend `Tagged` for this type specifically and add a custom `Codable` implementation to clean this up. The only problem is that the runtime always calls the default conditional conformance implementations rather than my custom ones.

This is a more general Swift question perhaps, but is there a way to override this implementation and make sure the runtime calls my version? Here's the code:

```swift
public struct User: Codable {

    public enum UserIdTag {}
    public typealias Id = Tagged<UserIdTag, String>

    let id: Id
}

extension Tagged where Tag == User.UserIdTag, RawValue == String {

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()

        do {
            try self.init(rawValue: String(container.decode(Int.self)))
        } catch {
            try self.init(rawValue: container.decode(String.self))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(Int(rawValue))
    }
}
```

**Comment by mbrandonw** [comment]
I don't think this is possible unfortunately :/

In your specific case you could decode the `id` as an `Tagged<User, Either<String, Int>>`, and then make a computed property on `User` for the `Tagged<User, Int>` version that you will use everywhere.

**Comment by Killectro** [comment]
That is a good idea, thanks for the speedy response. I'll probably tackle this in my second round of Tagged-related refactors.
