### ISSUE TITLE
Custom date decoding issue

### ISSUE THREAD

**Issue by buscarini** [pointfreeco/swift-tagged#23]
Hi, I updated to the latest version and I run into an issue with custom date decoding. I think commit 4e607f75cbead201343b9da14c2fab1e6ed98e7e broke that, and now a custom date decoding strategy can't be used for Tagged types, it is simply ignored. This seems like a swift bug to me, but for now I think the best option is to revert that change.

**Comment by stephencelis** [comment]
Hi @buscarini! Thanks for the report and sorry about that! Do you have some code that illustrates the issue?

**Comment by buscarini** [comment]
Yes, I was preparing a pull request, but here you go:

`func testDecodableCustomDates() {
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .custom { decoder in
      let seconds = try decoder.singleValueContainer().decode(Int.self)
      return Date(timeIntervalSince1970: TimeInterval(seconds))
    }
    
    XCTAssertEqual(
      [Date(timeIntervalSince1970: 1)],
      try decoder.decode([Date].self, from: Data("[1]".utf8))
    )
    
    XCTAssertEqual(
      [Tagged<Tag, Date>(rawValue: Date(timeIntervalSince1970: 1))],
      try decoder.decode([Tagged<Tag, Date>].self, from: Data("[1]".utf8))
    )
  }`

Unfortunately, I've found out that changing this back makes another test fail. In that case wrapped optionals fail to decode if the json value is null. I haven't been able to find a solution to both issues for now.

**Comment by stephencelis** [comment]
@buscarini If I define `decode` as the following, both appear to work:

``` swift
extension Tagged: Decodable where RawValue: Decodable {
  public init(from decoder: Decoder) throws {
    do {
      self.init(rawValue: try decoder.singleValueContainer().decode(RawValue.self))
    } catch {
      self.init(rawValue: try .init(from: decoder))
    }
  }
}
```

I'm not sure what the repercussions are, and it does indeed feel like a shortcoming or bug of `Decodable`. Any thoughts? Would we need to handle `Encodable` in a similar way?

**Comment by buscarini** [comment]
:D Funny, I just made a pull request with the same solution. I think this should work fine, and I think it's the only reasonable solution for now. I even checked swift source code, and it seems initializing the date with the decoder directly doesn't hit the date decoding strategy, as this is done by the decoder before getting to the actual type. And solving the optional issue with the singleValueContainer would require to have different code depending on the type, which shouldn't even be possible in a generic function. 

As for the encodable protocol, I think it's going to have the same issue. I'll try to get some free time to put that in the pull request too.

**Comment by buscarini** [comment]
It seems that the encoding strategy doesn't require this, and just reverting the commit is enough to get it working.
