### ISSUE TITLE
Does `ExpressiblebyArrayLiteral` code still need to be commented out?

### ISSUE THREAD

**Issue by Ilya-Belenkiy-Rocket** [pointfreeco/swift-tagged#28]
https://github.com/pointfreeco/swift-tagged/blob/926e8e0c3d893481b94b418118898a8b9e530353/Sources/Tagged/Tagged.swift#L207

**Comment by stephencelis** [comment]
Now that the ABI is stabilizing, it might be safe. You can always paste this code into your own code base to give it a spin, though! We just wanna be careful about supporting something that might break in the future.

**Comment by stephencelis** [comment]
Fixed by #53!
