### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ericlewis** [pointfreeco/swift-tagged#58]
Hey all, I was just trying something out and ran into an odd issue. I am not entirely sure what the compiler is thinking.

The below code has a problem when it comes to decoding, with `JSONDecoder` throwing `Expected to decode Array<Any> but found a dictionary instead.` on `files`, what is interesting is if we change the type to: `[String: File]` it works perfectly fine. I didn't dig in to it much, but it seems like the `ExpressibleByArrayLiteral` conformance is being interpreted incorrectly. 

Problem code:
```swift
struct Gist {
  let id: Self.ID
  let files: [File.Name: File]

  typealias ID = Tagged<Self, String>
}

extension Gist: Identifiable {}
extension Gist: Codable {}

struct File {
  let filename: Name
  let content: String

  typealias Name = Tagged<Self, String>
}

extension File: Codable {}
```

**Comment by stephencelis** [comment]
Hi @ericlewis! There doesn’t appear to be any decoding code in your example above that would throw. Can you provide a full sample that reproduces the issue? There are definitely some gotchas around codability, some of which we can’t work around when it comes to coding containers, but if there is a bug we can fix we’d love to know!

**Comment by mbrandonw** [comment]
This is currently a Swift limitation in which only string and integer keys properly encode/decode into dictionaries. A fix has been proposed and accepted into Swift: https://github.com/apple/swift-evolution/blob/main/proposals/0320-codingkeyrepresentable.md

**Comment by ericlewis** [comment]
Ah! Seems like that is the case then @mbrandonw.

**Comment by ericlewis** [comment]
@stephencelis it just using a `JSONDecoder.decode(Gist.self, from: data)`. Nothing fancy. Brandon's reply seems to be the case.

**Comment by stephencelis** [comment]
@ericlewis That was one of the issues around decoding containers I was alluding to, just wanted to confirm what `data` was beforehand :)
