### ISSUE TITLE
CodingKeyRepresentable Conformance

### ISSUE THREAD

**Issue by aetherealtech** [pointfreeco/swift-tagged#65]
I just discovered that when a dictionary whose keys are a `Tagged` type, they get encoded as an array of alternating `{key}`, `{value}`, ... pairs instead of as an actual object.  This is a well known problem with Dictionaries of non "simple" key types (see [here](https://oleb.net/blog/2017/12/dictionary-codable-array/), and apparently a (relatively) new solution to this is to have the key type implement the `CodingKeyRepresentable` protocol.

I was able to add this conformance to `Tagged` as an extension, but it made me wonder if it makes sense for this conformance to be added to `Tagged` directly.

**Comment by stephencelis** [comment]
@aetherealtech That definitely sounds worth adding direct support for! Would you like to throw together a small PR that we can discuss?
